---
title: "useful_links"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## GitHub Documents

This is an R Markdown format used for publishing markdown documents to GitHub. When you click the **Knit** button all R code chunks are run and a markdown file (.md) suitable for publishing to GitHub is generated.

## Some Useful links

### Help in the CHANNEL

* https://blog.hootsuite.com/launch-youtube-channel-14-days/ 
* https://backlinko.com/hub/youtube/optimize

### RMarkdown editing

* https://github.com/holtzy/Pimp-my-rmd/blob/master/index.Rmd
* https://github.com/tgirke/reproducible/blob/master/sample.Rmd~
* https://bookdown.org/yihui/rmarkdown/
* https://rmarkdown.rstudio.com/flexdashboard/
* https://cran.r-project.org/web/packages/workflowr/vignettes/wflow-04-how-it-works.html
* https://buildmedia.readthedocs.org/media/pdf/reproducible-analysis-workshop/latest/reproducible-analysis-workshop.pdf 
* 

### GIT

https://github.com/MorgsBrew/Youtube_Colab/blob/master/x_reasons_to_drink_fermented_maize/2019-04-17-x-reasons-to.html

https://rawgit.com/MorgsBrew/Youtube_Colab/master/x_reasons_to_drink_fermented_maize/2019-04-17-x-reasons-to.html

```{r}
git remote set-url origin https://github.com/MorgsBrew/Youtube_Colab.git
```


### R Packages 

```{r, eval=FALSE}
# https://github.com/rstudio/rticles
install.packages("rticles")
install.packages("learnr")
```


